trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.6.6'

  # These secrets are stored securely in Azure DevOps Variables or Variable Group
  subscription_id: $(subscription_id)
  client_id: $(client_id)
  client_secret: $(client_secret)
  tenant_id: $(tenant_id)

stages:
- stage: Terraform
  jobs:
  - job: TerraformJob
    steps:
    - checkout: self

    - task: UseTerraform@0
      inputs:
        terraformVersion: $(terraformVersion)

    - script: |
        echo "Initializing Terraform..."
        terraform init -input=false
      displayName: 'Terraform Init'

    - script: |
        echo "Running Terraform Plan..."
        terraform plan \
          -var "subscription_id=$(subscription_id)" \
          -var "client_id=$(client_id)" \
          -var "client_secret=$(client_secret)" \
          -var "tenant_id=$(tenant_id)" \
          -var "resource_group_name=$(resource_group_name)" \
          -var "location=$(location)" \
          -out=tfplan
      displayName: 'Terraform Plan'

    - script: |
        echo "Applying Terraform..."
        terraform apply -input=false -auto-approve tfplan
      displayName: 'Terraform Apply'