trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.6.6'

stages:
- stage: Terraform
  jobs:
  - job: TerraformJob
    steps:
    - checkout: self

    - script: |
        echo "Installing Terraform..."
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl unzip
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o hashicorp.gpg
        sudo install -o root -g root -m 644 hashicorp.gpg /usr/share/keyrings/
        sudo tee /etc/apt/sources.list.d/hashicorp.list <<EOF
        deb [signed-by=/usr/share/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main
        EOF
        sudo apt-get update && sudo apt-get install terraform=$(terraformVersion)
        terraform version
      displayName: 'Install Terraform'

    - script: |
        terraform init -input=false
      displayName: 'Terraform Init'

    - script: |
        terraform plan \
          -var "subscription_id=$(subscription_id)" \
          -var "client_id=$(client_id)" \
          -var "client_secret=$(client_secret)" \
          -var "tenant_id=$(tenant_id)" \
          -var "resource_group_name=$(resource_group_name)" \
          -var "location=$(location)" \
          -out=tfplan
      displayName: 'Terraform Plan'

    - script: |
        terraform apply -input=false -auto-approve tfplan
      displayName: 'Terraform Apply'