trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.6.6'

stages:
- stage: Terraform
  jobs:
  - job: TerraformJob
    steps:
    - checkout: self

    - script: |
        echo "Installing Terraform v${terraformVersion}..."

        # Download Terraform zip
        curl -O https://releases.hashicorp.com/terraform/${terraformVersion}/terraform_${terraformVersion}_linux_amd64.zip

        # Unzip and move binary
        unzip terraform_${terraformVersion}_linux_amd64.zip
        sudo mv terraform /usr/local/bin/

        # Verify install
        terraform version
      displayName: 'Install Terraform'

    - script: |
        terraform init -input=false
      displayName: 'Terraform Init'

    - script: |
        terraform plan \
          -var "subscription_id=$(subscription_id)" \
          -var "client_id=$(client_id)" \
          -var "client_secret=$(client_secret)" \
          -var "tenant_id=$(tenant_id)" \
          -var "resource_group_name=$(resource_group_name)" \
          -var "location=$(location)" \
          -out=tfplan
      displayName: 'Terraform Plan'

    - script: |
        terraform apply -input=false -auto-approve tfplan
      displayName: 'Terraform Apply'
